export const AIR_CONDITION = {
  CHANGE_TEMPERATURE: 'AIR_CONDITION_CHANGE_TEMPERATURE',
  CHANGE_MODE: 'AIR_CONDITION_CHANGE_MODE',
  CHANGE_STATE: 'AIR_CONDITION_CHANGE_STATE',
  CHANGE_FAN: 'AIR_CONDITION_CHANGE_FAN',
};